[project]
name = "pegasus"
version = "0.1"
description = "CLI for Django and SaaSPegasus"
readme = "README.md"
authors = [{name = "saaspegasus"}]
license = {text = "Apache-2.0"}
requires-python = ">=3.8"
classifiers = [
    "License :: OSI Approved :: Apache Software License"
]
dependencies = [
    "click"
]

[project.urls]
Homepage = "https://github.com/saaspegasus/pegasus-cli"
Changelog = "https://github.com/saaspegasus/pegasus-cli/releases"
Issues = "https://github.com/saaspegasus/pegasus-cli/issues"
CI = "https://github.com/saaspegasus/pegasus-cli/actions"

[project.entry-points.console_scripts]
pegasus = "pegasus.cli:cli"

[project.optional-dependencies]
dev = ["pytest", "ruff", "pre-commit"]
